name: Build and Release Extension

on:
    push:
        tags:
            - "v*" # Activates on tag starting with "v"

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            # Chrome/Chromium
            - name: Build Chrome Extension
              run: |
                  mkdir -p dist/chrome
                  cp -r src/* dist/chrome/
                  cp manifests/manifest.chromium.json dist/chrome/manifest.json
                  cd dist/chrome && zip -r ../../pubmed-to-bibtex-chrome.zip . && cd ../..

            # Firefox
            - name: Build Firefox Extension
              run: |
                  mkdir -p dist/firefox
                  cp -r src/* dist/firefox/
                  cp manifests/manifest.firefox.json dist/firefox/manifest.json
                  cd dist/firefox && zip -r ../../pubmed-to-bibtex-firefox.zip . && cd ../..

            # Create a github release and load the zip files
            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  files: |
                      pubmed-to-bibtex-chrome.zip
                      pubmed-to-bibtex-firefox.zip
                  body: "New version of this extension is ready to install!"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
